application: ubersimplesupport
version: 0-0-1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /req/.*
  script: main_requestor.py
  #login: required
 
- url: /res/.*
  script: main_responder.py
  login: required
 
- url: /.*
  script: index.py
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*/_svn/.*

builtins:
- remote_api: on
- datastore_admin: on